55 expfit
matchms/matchms-backup pull request #108
Opened 2020-04-10 20:36 UTC by jspaaks

2020-04-11 14:29 UTC, florian-huber commented on tests/test_clean_inchis.py
> -def test_clean_inchis():
Just to better understand where it's going: was this test removed because the code it is supposed to test is likely to change radically anyway. Or because it used the non-synthetic test data?

2020-04-11 14:32 UTC, florian-huber requested changes
The new added plotting functions look really nice. Thanks @jspaaks!
The structure of it looks fine to me. I will need more time, however, to test it on some real spectra and see how it performs in comparison to what I had before. But that shouldn't stop this pull request form being merged.

2020-04-11 21:45 UTC, jspaaks commented on tests/test_clean_inchis.py
> -def test_clean_inchis():
Neither. I think what happened is:
- this test was failing for me
- I did not see how to fix it due to https://github.com/matchms/matchms/issues/99#issue-597320421
- I deleted the file for the time being while i was developing
- but then I accidentally commited the deletion.

I have brought it back from the dead, but it is still failing. Could you see if you can fix it @florian-huber ?

2020-04-12 09:08 UTC, jspaaks commented on tests/test_clean_inchis.py
> -def test_clean_inchis():
**Update** I found what was wrong: I broke ``Spectrum.clone`` when I worked on the getters. Should be corrected now.

2020-04-12 09:10 UTC, jspaaks commented on tests/test_clean_inchis.py
> -def test_clean_inchis():
If you think this conversation is resolved, go ahead and mark it as such.

2020-04-13 13:32 UTC, florian-huber commented on tests/test_clean_inchis.py
> -def test_clean_inchis():
Looks good. Thanks!

2020-04-13 13:32 UTC, florian-huber approved these changes

2020-04-13 14:13 UTC, jspaaks commented
Thank you for reviewing this!

2020-04-13 14:13 UTC, merged