58 cosine greedy
matchms/matchms-backup pull request #112
Opened 2020-04-11 21:32 UTC by jspaaks

Added cosine greedy equivalent to https://github.com/matchms/old-iomega-spec2vec/blob/216b8f8b5e4ffd320b4575326a05fb6c7cd28223/matchms/old/ms_similarity_classical.py#L120-L182

with tests equivalent to 
https://github.com/matchms/old-iomega-spec2vec/blob/216b8f8b5e4ffd320b4575326a05fb6c7cd28223/tests/old/test_ms_similarity_classical.py#L17-L53

Under the hood, the implementation is different though. This PR is using vectorized operations / matrix operations where the old code was doing more looping. Hoipefully this way will be easier to read as well as more performant.

2020-04-15 07:55 UTC, florian-huber approved these changes
Really nice solution @jspaaks !
I had another vector based alternative in the past as well (``cosine_matrix_fast``), but that was working with binning and not tolerances, so it gave slightly different values than the "original" cosine implementation. I checked your version against the original code and it seems to match perfectly. I haven't checked if there is a real gain in performance though, have you? (might also depend on spectrum size)

2020-04-15 07:57 UTC, florian-huber commented
@jspaaks I slightly modified the test function. I added some spectra that I used to figure out if it indeed gave me the same results than the "original" score, which contains some non-trival peak mixture that tends to go wrong with too simple cosine score implementation. But feel free to change.

2020-04-15 09:00 UTC, florian-huber commented
Just realized that your function does return the score, but not the number of matching peaks. MS people often select scores based on how many matching peaks this is based on (``min_match``). 
I now added it and hope I didn't mess up your code too much (feel free to implement it differently).

2020-04-15 09:22 UTC, florian-huber approved these changes
@jspaaks I added the number of matching peaks to your CosineGreedy output since that is in practice often used for lowering the risk of having too many false positives (people would for instance only take cosine scores for pairs with minimum 2, or 5 matches). Hope this doesn't screw up things you had planed down the line?

2020-04-15 15:27 UTC, jspaaks commented
Hi Florian,
just a note on process: it is customary to not append commits to somebody else's pull request --instead you should leave your suggestions as comments, or possibly as issues to work on later. 

Could you roll back your commits on ``58-cosine-greedy``? The easiest way to do so is probably

1. make a branch ``cosine-greedy-tuple-output`` off of this branch (including your changes)

    ```
    git checkout 58-cosine-greedy
    git checkout -b cosine-greedy-tuple-output
    git checkout 58-cosine-greedy
    ```
1. Revert the commits by adding a new commit:

    ```
    git revert 788ca1d
    ```
1. Resolve the conflicts by picking the HEAD part and deleting the other part.
1. git add and commit your resolved file, then push the resolve commit to this branch.

If I would be doing the review, I would add one or more comments, something along the lines of "this unit test is not discriminatory enough", "units test should use the same spectrum combination", and/or "add a unit test that tests whether the argument order matters" with the permalink to the code that I'm talking about, or by leaving it as a comment in the 'margin' of the diff.

Secondly, I would make a new issue that says "CosineGreedy should return score as well as n_peaks", and in the body describe why you think that is needed. That could then be the start of a discussion there, resulting in a plan on how to implement it, which then would be done in a branch, which could then become its own PR.

As to your question https://github.com/matchms/matchms/pull/112#pullrequestreview-393537745 about performance: I have not compared one against the other, but I would assume that vectorized matrix operations are faster than looping, even for spectrums with many peaks. 

Thanks for reviewing and let me know if I can help you in some way,
-Jurriaan

2020-04-15 19:50 UTC, florian-huber commented on matchms/similarity/CosineGreedy.py
> +            return score
Since MS people use the cosine score and also the number of matching peaks found, it would be better if this function would return both values, e.g. (score, n_matches).

2020-04-15 19:52 UTC, florian-huber commented on tests/test_cosine_greedy.py
> +    spectrum_1 = Spectrum(mz=numpy.array([100, 150, 200, 300, 500, 510, 1100], dtype="float"),
One common thing that too simple methods often get wrong is that each peak can only be match to ONE other peak in the other spectrum. So to test if this is done right it would maybe be better to use two spectra that have some peaks which overlap within the tolerance range.

2020-04-15 19:53 UTC, florian-huber requested changes
@jspaaks Sorry for adding my commits first. I kind of new and felt a bit guilty after pushing them, but I thought it would make things easier since I had done them anyway to test and understand your function. Will stick to the protocol next time :)
(for now I indeed reverted my commits and added my suggestions as comments)

2020-04-16 06:05 UTC, jspaaks commented on matchms/similarity/CosineGreedy.py
> +            return score
Good to know. However as this affects other parts of the code (e.g. ``.top()`` and ``.sort()`` on Scores), I think we should make a new issue about it, such that we can discuss how we are going to handle those changes. Let me know if you agree. The alternative would be to work it all into this PR.

2020-04-16 06:31 UTC, jspaaks commented on tests/test_cosine_greedy.py
> +    spectrum_1 = Spectrum(mz=numpy.array([100, 150, 200, 300, 500, 510, 1100], dtype="float"),
added as requested

2020-04-16 06:35 UTC, florian-huber commented on matchms/similarity/CosineGreedy.py
> +            return score
Maybe doing a new issue on this is indeed better. I'll make one for this since I expect that this will be more general a not only apply to the cosine score (other scores might also return a score and some extra quality measures...). So go ahead with the PR if you like!

2020-04-16 06:38 UTC, jspaaks commented
Hi Florian, thanks for rolling back. I made some changes, and suggested that we make the "return multiple values" issue a new issue, such that we can discuss the implications there, without blocking further developments based on this PR. Let me know what you think,
-Jurriaan

2020-04-16 06:48 UTC, florian-huber commented
Hi Juriaan, looks good. Thanks!
I made a new issue #118 for later modifying the cosine score returns.

2020-04-16 06:48 UTC, florian-huber approved these changes

2020-04-16 08:03 UTC, merged