114 convert spectrum to sentence
matchms/matchms-backup pull request #115
Opened 2020-04-12 17:01 UTC by jspaaks

- (not done yet)
- includes #113 

working on functionality for
- [x] converting a spectrum to a document
- [x] building (=training?) a spec2vec model
- [ ] calculating a spec2vec similarity score. (function works but returns ``1``.)

2020-04-22 12:28 UTC, florian-huber commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
I am not so comfortable with adding the spectrum to ``Document``. I can see that it has its merits for developing and testing the workflow, if that's the purpose, please just ignore my remark. But my thinking was:
- I wouldn't expect a "document" object to also contain the entire original spectrum object. 
- Spec2Vec is supposed to also work with non spectrum data.

However, I also don't have a better, clean solution for this. 
Maybe we could create a more generic parent class called ``Document`` and derive a mass spec specific child class, ``SpectrumDocument`` or something.

2020-04-22 12:40 UTC, florian-huber requested changes
Thanks Juriaan for this large piece of work!
Looks nice and clean. And will be easy to extend the missing functionalities (e.g. weighing words, ignore missing words option etc).
Only had one remark about including spectrum in ``Document`` object.

2020-04-22 13:54 UTC, jspaaks commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
> I wouldn't expect a "document" object to also contain the entire original spectrum object

I'm adding ``spectrum`` to the ``Document`` instance so that later on, when the user has completed their scores table according to the ``Spec2Vec`` similarity measure, you still have the spectrum information in the reference and query ``Document``s. That way, you can for example select the 10 best scores, retrieve their query-reference ``Document`` pair, and (for example) plot the 2 spectrums very easily; or you could go online to PubChem and look up more/better metadata for the handful of spectrums that you find interesting (instead of doing that for say all of the 150000 spectrums that were analyzed)

To me, putting ``spectrum`` in instances of ``Document`` is a clean way to get rid of keeping indexes of documents, such as 
- https://github.com/matchms/old-iomega-spec2vec/blob/216b8f8b5e4ffd320b4575326a05fb6c7cd28223/matchms/old/helper_functions.py#L164
- https://github.com/matchms/old-iomega-spec2vec/blob/216b8f8b5e4ffd320b4575326a05fb6c7cd28223/matchms/old/ms_functions.py#L820

Also, if we're going to have a ``SpectrumDocument``, I'd prefer to rename ``Document`` to ``SpectrumDocument``, and not have the parent class.

2020-04-22 14:13 UTC, florian-huber commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
The parent class was just a suggestion to have something like a template for people to create their own ``Document`` flavors. But renaming to ``SpectrumDocument`` is fine for me as well!
(for me it was simply about clearly indicating that it is a particular, spectrum-related style of document)

I also agree with you that it solves the cumbersome dealing with identifiers. And I assume the "workflow" for someone willing to use Spec2Vec on _whatever_-data would then just be to create a new ``WhateverDocument`` class and run Spec2Vec from there, right?

2020-04-22 16:46 UTC, jspaaks commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
More or less yes on ``WhateverDocument``. Basically, adapt how you make ``words`` out of whatever object you work with here:

https://github.com/matchms/matchms/blob/40c686d4bb9ae84860765498b3df8a3b6a7a730a/matchms/similarity/spec2vec/convert_spectrum_to_document.py#L1-L9

In the documentation and/or examples we should list the steps for people to use their own flavor of object.

2020-04-22 16:48 UTC, jspaaks commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
maybe the return  should be 

```python
return Document(object=spectrum, words=words) 
```

or 

```python
return SpectrumDocument(spectrum) 
```
(with conversion to words internal to ``SpectrumDocument``)

2020-04-22 19:32 UTC, florian-huber commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
I agree with adding steps to design an own flavor to the documentation!
And the variant that you suggested above seems a good, general solution to me:
```python
return Document(object=spectrum, words=words) 
```
Then people could easily parse any data type they want!

2020-04-23 10:48 UTC, jspaaks commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
Went with ``obj`` because ``object`` is a reserved word. Also had to delete the ``weights`` getter because ``Document`` is now agnostic to the type of ``obj``, therefore it can not be sure that ``obj`` has in fact a ``.intensities``. 

If you feel this resolves the conversation, please mark it as such, then I will merge this PR.

2020-04-23 11:20 UTC, florian-huber commented on matchms/similarity/spec2vec/Document.py
> +        self._spectrum = spectrum
Yes, thanks. That resolves it for me.

2020-04-23 11:21 UTC, florian-huber approved these changes

2020-04-23 11:21 UTC, florian-huber approved these changes

2020-04-23 11:26 UTC, merged

2020-04-23 11:26 UTC, jspaaks commented
Thanks for reviewing!