Add function to save spectrum to mgf file
matchms/matchms-backup pull request #121
Opened 2020-04-17 16:04 UTC by florian-huber

Aim: 

- Add function to save Spectrum (or list of Spectrum objects) to a single .mfg file.
- Add tests for new function.

2020-04-17 18:04 UTC, florian-huber commented
@jspaaks, should we also remove the dummy ``save`` function?

2020-04-17 18:33 UTC, jspaaks commented
> @jspaaks, should we also remove the dummy `save` function?

Yes, please do.

2020-04-17 18:44 UTC, jspaaks commented
Also relevant: pytest can make temporary directories for you https://docs.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture, might be cleaner.

2020-04-19 14:18 UTC, florian-huber commented
@jspaaks thanks for the hint with pytest temporary directories. 
Pylint will now complain either that I don't provide the variable in the __main__ part or that it doesn't know it. Can you let me know how I implement it? (or point me the right way)
Thanks!

2020-04-20 13:45 UTC, jspaaks commented
For me it works when using ``tmpdir``, but something is going wrong in writing the file becasue I have 
```
END IONS

```
in ``/tmp/<multiple subdirs>/test.mgf``

We can look at it later if you want.

2020-04-21 08:16 UTC, jspaaks requested changes
Good stuff. My only comment would be to change ``spectra`` to ``spectrums``, 
- because of consistency with the rest of the code
- because ``spectra`` is an ambiguous term: some people confuse it for the singular. With ``spectrums`` that confusion does not happen.

2020-04-21 08:55 UTC, florian-huber commented
I changed spectra to spectrums following review comment.

2020-04-21 09:43 UTC, jspaaks approved these changes

2020-04-21 13:26 UTC, florian-huber commented
Thanks for the review @jspaaks!

2020-04-21 13:26 UTC, merged