Add complete_compound_annotation() function
matchms/matchms-backup pull request #127
Opened 2020-04-19 20:13 UTC by florian-huber

- add complete_compound_annotation() function
- minor changes to clean_inchis function

2020-04-21 09:39 UTC, jspaaks requested changes

2020-04-21 09:39 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
This function is doing too much. I suggest breaking it up into these new filter functions:
1. ``derive_inchi_from_smiles``
1. ``derive_smiles_from_inchi``
1. ``derive inchikey_for_inchi``
1. ``harmonize_inchi``

Furthermore the ``if`` conditions are quite taxing on my brain. I suggest introducing two new subfunctions, for example for the first case, you'd make ``has_smiles`` and ``has_inchi`` that each wrap the logic now contained in the nested ``if`` statement. Sidenote: I find the ``if not inchi`` syntax difficult to process, see if you can use ``if inchi is None``. Generally speaking human brains process definite concepts better than non-definite, so try to say what ``is``, not what ``not is``.

2020-04-21 13:02 UTC, florian-huber commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
Sounds good to me. 
But I have one question regarding ``has_smiles`` and ``has_inchi``. Would you make it part of utils or add it to the Spectrum functions. Adding to Spectrum functions will be nicer to call, e.g. ``if spectrum.has_smiles:``, but it also means adding more functions to the class.

2020-04-21 13:38 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
Neither, I would add them as a subfunctions of e.g. ``derive_inchi_from_smiles``; they do not need to be exposed.

```python

def derive_inchi_from_smiles():

def has_inchi():
   empty_entry_types = ["some", "strings", "specific", "to inchi only"]
   return inchi is not None or inchi in empty_entry_types or len(inchi) < 12

def has_smiles():
   # something similar to above

inchi = spectrum.get("inchi")
smiles = spectrum.get("smiles")

if has_smiles() and not has_inchi():
    # do work to derive inchi from smiles

```

2020-04-21 13:46 UTC, florian-huber commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
But why not adding it to the utils then?
It just feels odd to define the exact same functions in at least 3 filter functions, maybe more.

Maybe we could also turn this around and not look for empty/None entries, but define functions like ``is_inchi()``, ``is_smiles()``, ``is_inchikey()``. Those would also be useful for additional cleaning steps. Now we already have some kind of is_smiles in the ``clean_inchis()`` function. And looking at the data again I saw that we also have many inchikeys among the inchis.

2020-04-21 17:34 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
Indeed don't copy-paste the same function 3 times. What about putting each function in its own file in ``matchms.filtering`` but not add them to ``matchms.filtering.__init__``? That way the three filters can
```python
from .has_inchi import has_inchi
```

2020-04-21 17:35 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
sorry I just saw my comment was too late. I can branch off of this if you want, just let me know.

2020-04-21 19:03 UTC, florian-huber commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
I indeed first implemented them now the way you first suggested. 
But I think we should maybe change it a bit.
Not the functions are called `` has_...`` which is not ideal in two ways. First, it doesn't actually check if the content is indeed a smiles, inchi, or inchikey but only checks if it is not "empty". And second, it contains a lot of `` not is`` logic, which I would agree with you is hard to read.

I suggest switching to either:
- ``smiles_is_empty()`` instead of ``has_smiles()``, or
- indeed implement proper ``is_smiles()`` or `` has_smiles()`` functions which then actually check if the format fits a smile, inchi, inchikey...  

What do you think?

2020-04-21 19:36 UTC, florian-huber commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
Observation: Working next to playing, running kids leads to way to many tiny (error-prone) micro-commits...

2020-04-22 11:59 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
I've created PR https://github.com/matchms/matchms/pull/145, let me know what you think.

2020-04-22 12:44 UTC, florian-huber commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
With your PR it seems good to me now. Only thing I didn't add is the above suggested ``harmonize_inchi()`` filter, because that is already part of ``clean_inchis``.

2020-04-22 13:59 UTC, jspaaks commented on matchms/filtering/complete_compound_annotation.py
> +from matchms.utils import mol_converter
Good with me

2020-04-22 14:00 UTC, jspaaks approved these changes
Good to merge.

2020-04-22 14:03 UTC, florian-huber commented
Thanks @jspaaks for reviewing and refactoring!

2020-04-22 14:04 UTC, merged