Various fixes
matchms/matchms-backup pull request #147
Opened 2020-04-22 17:01 UTC by jspaaks

Various of small fixes, like

- removed ``label`` argument from similarity function
- added argument ``known_adducts`` to ``derive_ionmode``
- added caching of ``load_adducts`` function result (#144)
- made user workflow integration test more challenging to pass

2020-04-22 17:08 UTC, jspaaks commented
@florian-huber could you check if the filters I'm using in ``integration-tests/test_user_workflow.py`` make sense (also wrt the order in which they are called, and the parameterization)? Other comments also welcome of course.

2020-04-22 19:45 UTC, florian-huber commented on matchms/filtering/derive_ionmode.py
> +    if known_adducts is None:
I was confused by the default of ``known_adducts=None``, which made me expect that the function knows no adducts (I already wanted to complain that this seems no good default ...). Would it be possible to use another flag, maybe ``known_adducts='default'``?

2020-04-22 19:50 UTC, florian-huber requested changes
The integration test looks good @jspaaks, also the used filters (and their order) !
I just left one small remark about a the default for ``add_adduct()`` (nothing close to my heart, so feel free to override). 
Nice fix with the caching of the adducts loading by the way.

2020-04-23 11:17 UTC, jspaaks commented on matchms/filtering/derive_ionmode.py
> +    if known_adducts is None:
I changed it such that you can put in the filename if you want to use your own adducts file. Most users will want the default; they dont have to specify anything. Regardless of which they choose, the caching will still work so performance is unaffected.

2020-04-23 11:29 UTC, florian-huber commented on matchms/filtering/derive_ionmode.py
> +    if known_adducts is None:
That solves it for me, thanks!

2020-04-23 11:29 UTC, florian-huber approved these changes

2020-04-23 11:41 UTC, merged