Add new test case and corresponding fix to filter
matchms/matchms-backup pull request #155
Opened 2020-04-23 14:41 UTC by florian-huber

When working on the actual data ``require_minimum_number_of_peaks`` failed because of ``TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'``. 
I added this to the tests and fixed the filter function.

2020-04-23 17:57 UTC, jspaaks requested changes
Nice repair and good that you added a test for it to avoid future regressions. 

Small request: could you use double quotes around strings whenever possible for consistency throughout the project? Thanks!

2020-04-23 19:42 UTC, florian-huber commented
Thanks @jspaaks. I'll also keep an eye on the strings! 
But this was not pointing at anything in this PR, right? Or did I miss anything?

2020-04-24 09:56 UTC, jspaaks commented
I was referring to the numpy ``dtype`` arguments in tests/test_require_minimum_number_of_peaks.py

2020-04-24 10:31 UTC, florian-huber commented
I changed the strings to ``dtype="float"``.

2020-04-24 13:58 UTC, jspaaks approved these changes

2020-04-25 12:59 UTC, florian-huber commented
Thanks for the review Juriaan!

2020-04-25 12:59 UTC, merged