Fix workflow in integration test.
matchms/matchms-backup pull request #156
Opened 2020-04-23 15:37 UTC by florian-huber

I overlooked one step in the integration test workflow. Usually I would put the ``require_minimum_number_of_peaks`` last, because other filters such as ``select_by_relative_intensity`` or ``select_by_mz`` will also potentially remove peaks (so one could end up with spectra having less peaks than required). 

When running it with the entire raw data, the adapted integration workflow failed when empty spectra were passed (not spectrums which are 'None', but spectrums that contain empty empty arrays of peaks).

- I changed the order of the filters in the integration test.
- I added tests for spectrums with empty peak arrays.
- I fixed ``normalize_intensities`` and ``select_by_relative_intensity`` so that they won't fail when facing empty intensity arrays.

2020-04-23 18:06 UTC, jspaaks requested changes

2020-04-23 18:06 UTC, jspaaks commented on tests/test_normalize_intensities.py
> +                           metadata={"testfield": "TEST"})
Why does this unit test have ``metadata``? The point of the test is ``mz`` and ``intensities`` being empty arrays, right?

2020-04-23 18:06 UTC, jspaaks commented on tests/test_select_by_relative_intensity.py
> +                           metadata={"testfield": "TEST"})
Why does this unit test have metadata? The point of the test is ``mz`` and ``intensities`` being empty arrays, right?

2020-04-23 18:07 UTC, jspaaks commented
BTW be aware that the changes in #150 will affect basically everything we had up to this point, so probably good to take a look at that before any other work.

2020-04-23 19:34 UTC, florian-huber commented on tests/test_select_by_relative_intensity.py
> +                           metadata={"testfield": "TEST"})
True! I removed the metadata from the test.

2020-04-23 19:34 UTC, florian-huber commented on tests/test_normalize_intensities.py
> +                           metadata={"testfield": "TEST"})
True! I removed the metadata from the test.

2020-04-24 10:00 UTC, jspaaks approved these changes

2020-04-24 10:35 UTC, florian-huber commented
@jspaaks Do you want to merge the different PRs? 
#155 and then #156 will after merging probably imply some changes according to #150.

2020-04-24 14:02 UTC, jspaaks commented
I think I'm right in saying that
- #155 can now be merged into master
- this should make #156 mergable (I didn't check btw)
- #158 can be merged

If you agree, then feel free to go ahead and merge them (also delete any of your branches after they have been merged)

And then I will merge #150 sometime next week, but I wanted to give the others opportunity to comment, even though @fdiblen kindly approved the PR already.

2020-04-25 13:23 UTC, florian-huber commented
Thanks for reviewing Juriaan!

2020-04-25 13:24 UTC, merged

2020-11-25 14:50 UTC, sverhoeven commented on matchms/similarity/PrecursormzMatch.py
> +    Example to calculate scores between 2 spectrums and iterate over the scores
I see 4 spectrums or 2 pairs of spectrums 
```suggestion
    Example to calculate scores between 2 pairs of spectrums and iterate over the scores
```