remove int() from function
matchms/matchms-backup pull request #158
Opened 2020-04-23 20:05 UTC by florian-huber

2020-04-24 10:12 UTC, jspaaks requested changes

2020-04-24 10:12 UTC, jspaaks commented on matchms/filtering/add_parent_mass.py
> +            parent_mass -= charge * PROTON_MASS
1. ln line 19, you multiply a variable ``precursor_mass`` by ``charge`` to get a mass, which leads me to believe that ``precursor_mass`` should be renamed ``precursor_mz``, correct?
1. In line 20, you're reusing the variable name ``parent_mass``. This is generally frowned upon, because now I'm not sure anymore what the conceptual meaning of ``parent_mass`` is: do you mean ``parent_mass`` as defined in line 19, or ``parent_mass`` in line 20? Perhaps you could make it something like:

   ```python
   protons_mass = PROTON_MASS * charge
   precursor_mass = precursor_mz * abs(charge)
   parent_mass = precursor_mass - protons_mass
   ``` 

   (if that is actually what is being calculated of course)

2020-04-24 10:21 UTC, florian-huber commented on matchms/filtering/add_parent_mass.py
> +            parent_mass -= charge * PROTON_MASS
Now you caught me using terms wrongly in a way I before complained about myself... 
Good suggestions to make code easier to understand! Thanks. I of course added it.

2020-04-24 13:55 UTC, jspaaks commented on matchms/filtering/add_parent_mass.py
> +            parent_mass -= charge * PROTON_MASS
No worries, that's why code reviews are useful, just having a second set of eyes is sometimes all it takes.

2020-04-24 13:56 UTC, jspaaks approved these changes

2020-04-25 13:25 UTC, florian-huber commented
Thanks for the review!

2020-04-25 13:25 UTC, merged