Scores is an iterator
matchms/matchms-backup pull request #159
Opened 2020-04-24 13:49 UTC by jspaaks

- ``calculate_scores`` now returns an iterator with ``list`` of ``(reference, query, *scores)``
- ``CosineGreedy`` returns the scores as well as the number of matches as a tuple
- refs #118 
- refs https://github.com/matchms/matchms/issues/118#issuecomment-616653050 (but the order is reference, query)

2020-04-26 18:17 UTC, florian-huber commented on matchms/Scores.py
> +        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
I think it would be better to leave the looping to the similarity function. 
That will give more freedom for optimization to the respective similarity functions. In some cases those functions will indeed iterate as described here, but for other (e.g. spec2vec) an alternative approach would be much more favorable (see #163). 
``calculate(self)`` will anyway aim to return a ``_scores`` array, so it should be enough to here call 
```python
self._scores = self.similarity_function(self.references[:self.n_rows, 0], self.queries[0, :self.n_cols])
return self
```

2020-04-28 07:51 UTC, jspaaks commented on matchms/Scores.py
> +        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
No the looping here is intentionally naive.

When we can demonstrate that we can reproduce your earlier analysis, we will start working on https://github.com/matchms/matchms/issues/74, and as a sub problem of that, https://github.com/matchms/matchms/issues/163.

2020-04-28 12:16 UTC, florian-huber commented on matchms/Scores.py
> +        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
As long as I can bypass this locally by getting spectrum vectors from a Spec2Vec class method (as for instance implemented in #165) we can also postpone it a bit. 
However, with the current implementation it is hard/annoying to redo the original calculation because the difference in performance is quite big and it seems to take >10hours to calculate a spec2vec similarity matrix for 10,000x10,000 pairs.

2020-04-29 07:38 UTC, jspaaks commented on matchms/Scores.py
> +        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
I think we should continue this discussion under #74 or #163. If you agree, would you mark this conversation as resolved? Thanks!

2020-04-29 12:49 UTC, sverhoeven commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
Dont flatten, expect users to give a flat array already. Maybe add an assertion to check

2020-04-29 12:59 UTC, sverhoeven commented on tests/test_cosine_greedy.py
> +    score, _ = cosine_greedy(norm_spectrum_1, norm_spectrum_2)
`(score,) = cosine_greedy(norm_spectrum_1, norm_spectrum_2)` might be easier

2020-04-29 13:06 UTC, sverhoeven commented on tests/test_cosine_greedy.py
> +    score, _ = cosine_greedy(norm_spectrum_1, norm_spectrum_2)
Please test returned n_matches

2020-04-29 13:12 UTC, sverhoeven commented on tests/test_scores.py
> +    assert next(scores) == ("rrr", "qq", "rrrqq", 5)
Add unit test for reset_iterator()

2020-04-29 13:15 UTC, cwmeijer requested changes
mooi hoor!

2020-04-29 13:15 UTC, cwmeijer commented on matchms/Scores.py
> +    def reset_iterator(self):
Remove this because it is only used in a test and that can be solved differently.

2020-04-29 13:15 UTC, cwmeijer commented on integration-tests/test_user_workflow.py
> +        r, q, _, _ = scores.__next__()
Read scores to a list "list(scores)" so you can read it twice for the asserts below.

2020-04-29 13:25 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        filtered = [elem for elem in scores if elem[0] != elem[1] and elem[3] > 20]
Use `for ref,query,score,n_matches in` instead of elem[i]

2020-04-29 13:33 UTC, cwmeijer commented on integration-tests/test_user_workflow.py
> +        # sort by score
redundant comment. the code is clear

2020-04-29 13:40 UTC, cwmeijer commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
key = score
score = lambda elem: elem[0]
or get_score instead of score

2020-04-29 13:47 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        assert sorted_by_score[0][0] != sorted_by_score[0][1], "Self-comparisons should have been filtered out."
This tests the code line (26 and 28) in test, this test should be removed

2020-04-29 14:22 UTC, sverhoeven commented on tests/test_scores.py
> +    assert next(scores) == ("r", "q", "rq", 2)
Your not testing the StopIteration raising and the length of the scores.

Mabye replace with
```python
scores = list(scores)
expected = [(...), (...)]
assert scores == expected
```

2020-04-29 17:56 UTC, jspaaks commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
done

2020-04-29 17:56 UTC, jspaaks commented on tests/test_cosine_greedy.py
> +    score, _ = cosine_greedy(norm_spectrum_1, norm_spectrum_2)
done

2020-04-29 17:56 UTC, jspaaks commented on tests/test_scores.py
> +    assert next(scores) == ("rrr", "qq", "rrrqq", 5)
removed method altogether

2020-04-29 17:57 UTC, jspaaks commented on matchms/Scores.py
> +    def reset_iterator(self):
removed method

2020-04-29 17:59 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        r, q, _, _ = scores.__next__()
now reads into a list, but the two assert blocks were removed in favor of checking the results against a known results (although I had problems with hashing Spectrum objects and Spikes objects, so I;m now only checking against score values and number of matches

2020-04-29 18:00 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        filtered = [elem for elem in scores if elem[0] != elem[1] and elem[3] > 20]
done

2020-04-29 18:00 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        # sort by score
comment removed

2020-04-29 18:02 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
changed it to get_score, but turns out assigning a lambda is a violation of pep --reverted change

2020-04-29 18:03 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        assert sorted_by_score[0][0] != sorted_by_score[0][1], "Self-comparisons should have been filtered out."
two assert blocks removed in favor of testing against a known result (although I had problems with hashing Spectrum objects and Spikes objects, so I;m now only checking against score values and number of matches)

2020-04-29 18:04 UTC, jspaaks commented on tests/test_scores.py
> +    assert next(scores) == ("r", "q", "rq", 2)
done

2020-04-29 18:12 UTC, jspaaks commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
also collected the asserts for input checking in a static method

2020-04-29 18:56 UTC, florian-huber commented on integration-tests/test_user_workflow.py
> +                if reference != query and n_matching > 20]
Minor thing: In the comment you say "at least 20 matching peaks", which would be ``>=20`` I think.

2020-04-29 19:10 UTC, florian-huber approved these changes
Looks good Juriaan!
(feel free to skip the tiny comment I left)

2020-04-30 08:56 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +                if reference != query and n_matching > 20]
fixed it with ``>=``

2020-04-30 10:34 UTC, sverhoeven commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
About the validation/ input check:
Only allowing a list might be too restrictive, a user might want to pass in a tuple or numpy array.
The check is OK for now and the check can be relaxed later if needed.

2020-04-30 10:34 UTC, sverhoeven commented on tests/test_cosine_greedy.py
> +    score, _ = cosine_greedy(norm_spectrum_1, norm_spectrum_2)
great

2020-04-30 10:34 UTC, sverhoeven commented on tests/test_scores.py
> +    assert next(scores) == ("rrr", "qq", "rrrqq", 5)
even better

2020-04-30 10:37 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        filtered = [elem for elem in scores if elem[0] != elem[1] and elem[3] > 20]
much clearer with use a list comprehension twice to get a different tuple member.

2020-04-30 11:09 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        assert sorted_by_score[0][0] != sorted_by_score[0][1], "Self-comparisons should have been filtered out."
I got the indices and with test below you can also compare the spectrums

```python
    expected = [
        (references[48], queries[50], pytest.approx(0.9994510368270997, rel=1e-9), 25), 
        (references[50], queries[48], pytest.approx(0.9994510368270997, rel=1e-9), 25), 
        (references[46], queries[48], pytest.approx(0.9981252309590571, rel=1e-9), 27), 
        (references[48], queries[46], pytest.approx(0.9981252309590571, rel=1e-9), 27), 
        (references[46], queries[50], pytest.approx(0.9979632203390496, rel=1e-9), 22), 
        (references[50], queries[46], pytest.approx(0.9979632203390496, rel=1e-9), 22), 
        (references[73], queries[74], pytest.approx(0.9956795920716246, rel=1e-9), 23), 
        (references[74], queries[73], pytest.approx(0.9956795920716246, rel=1e-9), 23), 
        (references[57], queries[59], pytest.approx(0.9886557001269415, rel=1e-9), 46),
        (references[59], queries[57], pytest.approx(0.9886557001269415, rel=1e-9), 46),
    ]
    assert actual_top10 == expected
```

2020-04-30 11:59 UTC, sverhoeven commented on tests/test_scores.py
> +    assert next(scores) == ("r", "q", "rq", 2)
thanks

2020-04-30 12:08 UTC, jspaaks commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
Agreed. Maybe ``Iterable`` could be an option.

2020-04-30 13:08 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        assert sorted_by_score[0][0] != sorted_by_score[0][1], "Self-comparisons should have been filtered out."
Changed it for cosine greedy user workflow, but for spec2vec the result is too unstable.

For future reference, I retrieved the indices like this
```python
print([(documents.index(actual_top10[i][0]),
        documents.index(actual_top10[i][1]),
        actual_top10[i][2]) for i, d in enumerate(actual_top10)])
```

2020-04-30 13:57 UTC, sverhoeven commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
Yes, Iterable is what I was looking for, please also change the typings in [Scores.__init__](https://github.com/matchms/matchms/blob/118-scores-iterator/matchms/Scores.py#L7) from `List[object]` to `Iterable[object]`

2020-04-30 14:00 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        assert sorted_by_score[0][0] != sorted_by_score[0][1], "Self-comparisons should have been filtered out."
That is a much easier way to get the indices, I was adding the r and c to return of scores.__next__

2020-04-30 14:38 UTC, jspaaks commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
Tried ``Iterable``, but that includes ``dict``, which gives weird results. Now changed to ``Union[List, Tuple, ndarray]`` and added some tests for each.

2020-04-30 14:43 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        r, q, _, _ = scores.__next__()
see also https://github.com/matchms/matchms/pull/159#discussion_r417327344

2020-05-04 12:07 UTC, sverhoeven commented on matchms/Scores.py
> +        self.n_rows = asarray(references).flatten().size
OK, nice compromise

2020-05-04 12:55 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
Def could work:

```python
def by_score(elements):
      score = elements[2]
      return score

sorted_by_score = sorted(filtered, key=by_score, reverse=True)
```

2020-05-04 13:46 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
I'm happy to make that change to a ``def`` if you want. Personally, I don't think it is an improvement. Reasons:
- I dislike the wide separation between the function definition and its use;
- Reading the function itself raises questions
- ~~The variable ``score`` in the ``def`` might be a violation of some style rule that says: you should ``return elements[2]`` immediately without creating ``score``~~ I just tried and it isn't

For reference, here's what it looks like

```python

def test_user_workflow():

    def apply_my_filters(s):
        s = default_filters(s)
        s = add_parent_mass(s)
        s = normalize_intensities(s)
        s = select_by_relative_intensity(s, intensity_from=0.0, intensity_to=1.0)
        s = select_by_mz(s, mz_from=0, mz_to=1000)
        s = require_minimum_number_of_peaks(s, n_required=5)
        return s

    def by_score(elements):
        score = elements[2]
        return score

    module_root = os.path.join(os.path.dirname(__file__), '..')
    spectrums_file = os.path.join(module_root, 'tests', 'pesticides.mgf')

    # apply my filters to the data
    spectrums = [apply_my_filters(s) for s in load_from_mgf(spectrums_file)]

    # omit spectrums that didn't qualify for analysis
    spectrums = [s for s in spectrums if s is not None]

    # this will be a library grouping analysis, so queries = references = spectrums
    queries = spectrums[:]
    references = spectrums[:]

    # define similarity function
    cosine_greedy = CosineGreedy()

    # calculate_scores
    scores = list(calculate_scores(references,
                                   queries,
                                   cosine_greedy))

    # filter out self-comparisons, require at least 20 matching peaks:
    filtered = [(reference, query, score, n_matching) for (reference, query, score, n_matching) in scores
                if reference != query and n_matching >= 20]

    sorted_by_score = sorted(filtered, key=by_score, reverse=True)

    actual_top10 = sorted_by_score[:10]

    expected_top10 = [
        (references[48], queries[50], pytest.approx(0.9994510368270997, rel=1e-9), 25),
        (references[50], queries[48], pytest.approx(0.9994510368270997, rel=1e-9), 25),
        (references[46], queries[48], pytest.approx(0.9981252309590571, rel=1e-9), 27),
        (references[48], queries[46], pytest.approx(0.9981252309590571, rel=1e-9), 27),
        (references[46], queries[50], pytest.approx(0.9979632203390496, rel=1e-9), 22),
        (references[50], queries[46], pytest.approx(0.9979632203390496, rel=1e-9), 22),
        (references[73], queries[74], pytest.approx(0.9956795920716246, rel=1e-9), 23),
        (references[74], queries[73], pytest.approx(0.9956795920716246, rel=1e-9), 23),
        (references[57], queries[59], pytest.approx(0.9886557001269415, rel=1e-9), 46),
        (references[59], queries[57], pytest.approx(0.9886557001269415, rel=1e-9), 46),
    ]
    assert actual_top10 == expected_top10

```

2020-05-04 13:46 UTC, jspaaks commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
And another alternative would be 

```python
sorted_by_score = sorted(filtered, key=lambda elem: dict(score=elem[2])["score"], reverse=True)
```

2020-05-04 14:00 UTC, sverhoeven commented on integration-tests/test_user_workflow.py
> +        sorted_by_score = sorted(filtered, key=lambda elem: elem[2], reverse=True)
Agree, dont like the alternative it is more complicated. Lets keep it as it is.

2020-05-04 14:00 UTC, sverhoeven commented
I resolved conversations started by @cwmeijer, it OK to be merged now.

2020-05-04 15:29 UTC, merged

2020-05-04 15:30 UTC, jspaaks commented
Thanks for reviewing @sverhoeven, @florian-huber and @cwmeijer!

2020-12-03 12:57 UTC, sverhoeven commented on matchms/similarity/spectrum_similarity_functions.py
> +    matching_pairs : numpy array
A normal array is returned. 
```suggestion
    matching_pairs : array
```

2020-12-03 12:59 UTC, sverhoeven commented on matchms/similarity/spectrum_similarity_functions.py
> +    matching_pairs : numpy array
Or let it return a numpy array. Then the `matching_pairs = numpy.array(matching_pairs)` elsewhere is no longer needed