update workflow names, rename configuration files and add build badges
matchms/matchms-backup pull request #174
Opened 2020-04-29 13:22 UTC by fdiblen

2020-04-29 15:00 UTC, sverhoeven requested changes

2020-04-29 15:00 UTC, sverhoeven commented on .github/workflows/pypi.yml
> +name: 'PYPI'
Change to `PyPI` as this is how PyPI calls it self.

2020-04-29 15:00 UTC, sverhoeven commented on README.rst
> +.. list-table:: **Build status**
Why did you pull the CI badges out of the fair-software.nl table?

I prefer to see the 3 CI badges in the Continuous integration row of the fair-software.nl table, because with the improved names they should not need a label above it.

2020-04-29 15:00 UTC, sverhoeven commented on README.rst
> +   :alt: Anaconda
Can you update the ':alt:' value to 'Anaconda build & publish on GitHub Action'  to distinquish it from the conda badge?

2020-04-29 15:00 UTC, sverhoeven commented on README.rst
> +   :alt: PYPI
Same as anaconda build badge. We will also add a PyPi badge at some point, for example https://github.com/NLeSC/dask-cassandra-loader. So we need to distinquish between the build and the published artifact.

2020-05-08 07:45 UTC, sverhoeven commented on .github/workflows/pypi.yml
> +name: 'PYPI'
```suggestion
name: 'PyPI'
```

2020-05-08 07:46 UTC, sverhoeven commented on README.rst
> +   :alt: PYPI
```suggestion
   :alt: PyPI
```

2020-05-08 15:45 UTC, fdiblen commented on .github/workflows/pypi.yml
> +name: 'PYPI'
done

2020-05-08 15:50 UTC, fdiblen commented on README.rst
> +.. list-table:: **Build status**
done

2020-05-08 15:53 UTC, fdiblen commented on README.rst
> +   :alt: Anaconda
done

2020-05-08 15:54 UTC, fdiblen commented on README.rst
> +   :alt: PYPI
done

2020-05-08 15:54 UTC, fdiblen commented on README.rst
> +   :alt: PYPI
done

2020-05-11 11:45 UTC, sverhoeven approved these changes

2020-05-11 12:14 UTC, merged