Switch from openbabel to rdkit
matchms/matchms-backup pull request #187
Opened 2020-05-06 20:15 UTC by florian-huber

- New ``mol_converter()`` function based on rdkit instead of openbabel.
I ran both old and new implementation side-by-side on the actual data, converting >10,000 smiles and inchi and got near identical performance. Due to the license issue (#129) the new implementation hence seems favorable to me.

2020-05-07 12:14 UTC, florian-huber commented
Sorry for potential confusion. I just added another test (test_is_valid_smiles) after marking this PR ready.

2020-05-07 13:17 UTC, jspaaks requested changes
(couple of minor requests)

2020-05-07 13:17 UTC, jspaaks commented on matchms/filtering/derive_inchi_from_smiles.py
>              inchi = inchi.replace('\n', '').replace('\t', '').replace('\r', '')
if this is equal to ``inchi.trim()``, I would prefer that.

2020-05-07 13:17 UTC, jspaaks commented on matchms/utils.py
>  from rdkit import Chem
I would prefer ``import rdkit``, and then use as ``rdkit.Chem.MolFromInchi``

2020-05-07 13:17 UTC, jspaaks commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
would it be useful to define some alias functions, that use ``_mol_converter`` internally?

```python
def convert_smiles_to_inchi(smiles)
   return _mol_converter(smiles, "smiles", "inchi")
```

2020-05-07 13:17 UTC, jspaaks commented on matchms/utils.py
> +        mol = Chem.MolFromInchi(mol_input.replace('"', ""))  # rdkit can't handle '"'
I think ``trim('"')`` is better, as it pertains to the leading and trailing characters only

2020-05-07 13:17 UTC, jspaaks commented on tests/test_utils.py
> +                  ]
I like this style better:
```python
inchi_true = [
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)",
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)"'
]
```

2020-05-07 13:17 UTC, jspaaks commented on tests/test_utils.py
> +                   ]
would it make sense to have all these strings raw?

2020-05-07 13:17 UTC, jspaaks commented on matchms/utils.py
> -from openbabel import openbabel as ob
btw If this PR makes ``openbabel`` obsolete, delete it from ``environment.yml`` (and ``setup.py`` if it's still there).

2020-05-07 13:17 UTC, jspaaks commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
Or replace ``mol_converter`` with smaller, more topical functions entirely.

2020-05-07 14:04 UTC, florian-huber commented on matchms/utils.py
>  from rdkit import Chem
Done in new commit.

2020-05-07 14:05 UTC, florian-huber commented on matchms/utils.py
> +        mol = Chem.MolFromInchi(mol_input.replace('"', ""))  # rdkit can't handle '"'
I never heard of ``.trim()``. I switched to ``.strip('"')``.

2020-05-07 14:08 UTC, florian-huber commented on matchms/filtering/derive_inchi_from_smiles.py
>              inchi = inchi.replace('\n', '').replace('\t', '').replace('\r', '')
I never heard of ``.trim()``. I switched to ``.rstrip()``.

2020-05-07 14:20 UTC, florian-huber commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
I tried to clean the function up and think it should look better now?

2020-05-07 14:25 UTC, florian-huber commented on tests/test_utils.py
> +                  ]
Fine for me. I changed it to (nearly) your suggested style.
```python
inchi_true = [
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)",
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)"'
    ]
```

2020-05-07 14:26 UTC, florian-huber commented on tests/test_utils.py
> +                   ]
Yes, maybe easier to read. Done.

2020-05-07 14:28 UTC, florian-huber commented on matchms/utils.py
> -from openbabel import openbabel as ob
Done.

2020-05-07 14:38 UTC, florian-huber commented on tests/test_utils.py
> +                  ]
Prospector said **no**.

2020-05-07 14:42 UTC, jspaaks commented on matchms/filtering/derive_inchi_from_smiles.py
>              inchi = inchi.replace('\n', '').replace('\t', '').replace('\r', '')
sorry, that's what i meant. (trim is javascript)

2020-05-07 14:54 UTC, florian-huber commented on matchms/utils.py
>  from rdkit import Chem
Unfortunately I got some errors: ``AttributeError: module 'rdkit' has no attribute 'Chem'``. So for now I'll switch back to ``from rdkit import Chem``.

2020-05-07 15:27 UTC, jspaaks commented on matchms/utils.py
>  from rdkit import Chem
ok sounds good

2020-05-07 15:32 UTC, jspaaks commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
No that's a bad idea, please use separate functions.

2020-05-07 15:40 UTC, florian-huber commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
You mean adding 4 wrapping functions: convert_smiles_to_inchi, convert_inchi_to_smiles, convert_inchi_to_inchikey, convert_smiles_to_inchikey that call mol_converter (or _mol_converter) ?

2020-05-07 16:17 UTC, jspaaks commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
Yes, or even better, separate functions that do not call ``mol_converter`` but do the subset of the work that ``mol_converter`` does now.

2020-05-07 16:18 UTC, jspaaks commented on matchms/utils.py
> +        mol = Chem.MolFromInchi(mol_input.replace('"', ""))  # rdkit can't handle '"'
sorry, that's what i meant. (trim is javascript)

2020-05-07 16:30 UTC, fdiblen commented on tests/test_utils.py
> +                  ]
I also prefer 
```
inchi_true = [
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)",
   "InChI=1S/C2H7N3/c1-5-2(3)4/h1H3,(H4,3,4,5)"'
]
```
prospector will not complain with this.

2020-05-08 11:34 UTC, florian-huber commented on tests/test_utils.py
> +                  ]
OK. Done.

2020-05-08 11:47 UTC, florian-huber commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
I now switched to specific ``convert_x_to_y`` functions, but they still call mol_converter. It just felt better to me that way (could also be silly). I think the reason is less redundant code, that it will be easier to use the function elsewhere separately, and that it can be extended more easily.
Anyway, let me know if that causes headaches!

2020-05-11 08:53 UTC, jspaaks commented on matchms/utils.py
>  def mol_converter(mol_input, input_type, output_type):
I propose we ask the others what they think is the cleaner pattern and why. But that doesnt need to block this PR's merge.

2020-05-11 08:54 UTC, jspaaks approved these changes
Good job!

2020-05-11 08:54 UTC, fdiblen commented
> * New implementation of `mol_converter()` function, now based on rdkit instead of openbabel.
> * With this we can in principle dump `openbabel` which would close #129.
> * Added tests for `mol_converter()`, `is_valid_smiles()`, and `is_valid_inchi()`.
> 
> I ran both old and new implementation side-by-side on the actual data, converting >10,000 smiles and inchi and got virtually identical performance. It turns out that one of the reasons it was performing poorly before is that rdkit sometimes has trouble handling InChI in the format `"InChI=..."` Also there are some smiles that cannot be converted using rdkit (but could when using openabel). But those can be fixed later using lookups (or be ignored).
> Due to the license issue (#129) the new implementation hence seems favorable to me.
> 
> **QUESTION:** should we also remove openbabel from the environment in this PR?

Answer to your **QUESTION**: Yes, if we are not going to use openbabel anymore, we should also remove it from the dependencies. Now we only use anaconda but not PyPi so we should update`meta.yml` and `environment.yml` only.

2020-05-11 09:12 UTC, merged

2020-05-11 09:12 UTC, florian-huber commented
Thanks Juriaan and Faruk for reviewing and commenting!