163 vectorized spec2vec
matchms/matchms-backup pull request #206
Opened 2020-05-12 14:19 UTC by jspaaks

2020-05-12 15:10 UTC, fdiblen commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    repository_root = os.path.join(os.path.dirname(__file__), '..')
use either single or double quote

2020-05-12 15:14 UTC, fdiblen commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    if os.path.isfile(model_file):
also check if file exists

2020-05-12 15:48 UTC, fdiblen commented on matchms/similarity/spec2vec/calc_vector.py
> +    vector = sum(word_vectors * weights_raised_tiled, 0)
use sum from numpy

2020-05-12 16:08 UTC, fdiblen approved these changes
:1st_place_medal:

2020-05-12 17:17 UTC, jspaaks commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    repository_root = os.path.join(os.path.dirname(__file__), '..')
done

2020-05-12 17:18 UTC, jspaaks commented on matchms/similarity/spec2vec/calc_vector.py
> +    vector = sum(word_vectors * weights_raised_tiled, 0)
done

2020-05-12 17:23 UTC, jspaaks commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    if os.path.isfile(model_file):
```python
os.path.isfile(model_file)
```
returns ``False`` for paths that are not a file or don't exist

2020-05-12 17:47 UTC, florian-huber requested changes
Thanks for implementing this so quickly. The parallel implementation looks good to me!

I am only in doubt if it is really necessary to have two separate calculate score methods. 
Is there any use-case where we would really need the pair-wise implementation?
Because if not, the workflow would look easier/cleaner with only one default option.
(shouldn't be blocking anything, we can also discuss it after this PR!)

2020-05-12 17:47 UTC, florian-huber commented on matchms/Scores.py
> +    def calculate_parallel(self):
I am a bit in doubt here.
Now we have both an implementation for pair-wise and parallel calculations.
But I am not sure if that is really necessary. In principle the calculate_parallel functions could be used for all scores and would also work for single pairs. Having both could even be distracting because now all scores need to come in two flavors, such as as Spec2VecParallel and Spec2Vec.

2020-05-13 08:55 UTC, jspaaks commented on matchms/Scores.py
> +    def calculate_parallel(self):
matchms needs to support both vectorized and naive calculation, because 
1. similarity functions are supplied by the user, which means they may or may not be vectorized.
1. testing of a vectorized algorithm is easier if you can compare against the naive implementation (which is typically a bit easier to read and understand)

Just to clarify: this does not imply that similarity functions need to "come in two flavors", quite the opposite actually.

2020-05-13 09:00 UTC, florian-huber commented on matchms/Scores.py
> +    def calculate_parallel(self):
OK, that makes sense. Thanks Juriaan.

2020-05-13 09:00 UTC, florian-huber approved these changes

2020-05-13 09:44 UTC, HannoSpreeuw commented on tests/test_scores.py
> +        ("r0", "q0", "r0q0", 4),
6 lines of code to describe this. Slightly error prone. Perhaps better described by some loop?

2020-05-13 09:45 UTC, HannoSpreeuw commented on tests/test_scores.py
> +        ("r0", "q0", "r0q0", 4),
Same comment as above. 6 lines of code. Maybe replace by a loop/iteration?

2020-05-13 09:55 UTC, HannoSpreeuw commented on integration-tests/test_user_workflow.py
> +    module_root = os.path.join(os.path.dirname(__file__), "..")
Why are double quotes preferable?

2020-05-13 09:56 UTC, HannoSpreeuw commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    expected_top10 = [
Why do these indices and pytest.approx arguments need to be hardcoded?

2020-05-13 10:12 UTC, HannoSpreeuw commented on tests/test_scores.py
> +        ("r0", "q0", "r0q0", 4),
Okay. Looping would hamper the test.

2020-05-13 10:12 UTC, HannoSpreeuw commented on tests/test_scores.py
> +        ("r0", "q0", "r0q0", 4),
37 actual = list (scores)

2020-05-13 10:13 UTC, HannoSpreeuw commented on tests/test_scores.py
> +        ("r0", "q0", "r0q0", 4),
Same explanation by Jurriaan.

2020-05-13 10:14 UTC, HannoSpreeuw commented on integration-tests/test_user_workflow.py
> +    module_root = os.path.join(os.path.dirname(__file__), "..")
Ah. For reasons of consistency.

2020-05-13 10:16 UTC, HannoSpreeuw commented on integration-tests/test_user_workflow_spec2vec_parallel.py
> +    expected_top10 = [
For testing purposes this needs to be hardcoded.

2020-05-13 10:27 UTC, merged