Added release instructions
matchms/matchms-backup pull request #217
Opened 2020-05-13 13:04 UTC by sverhoeven

2020-05-13 13:31 UTC, jspaaks requested changes

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +
I expected this at the bottom of the README under a new section _For maintainers_

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +1. Check author list in citation.cff and .zenodo.json
``CITATION.cff`` and ``.zenodo.json``

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +1. Check author list in citation.cff and .zenodo.json
Maybe we should make this a Markdown file?

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +2. Bump the version using `bump2version <major|minor|patch>`
double backticks in restructured text

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +4. Goto [GitHub release page](https://github.com/matchms/matchms/releases)
link is currently Markdown format

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +A GitHub action will run which will publish the new version to anaconda.
maybe add hyperlink to the place on Anaconda cloud https://anaconda.org/nlesc/matchms

2020-05-13 13:31 UTC, jspaaks commented on CONTRIBUTING.rst
> +Also a Zenodo entry will be made for the release with it's own DOI.
``its`` (because it's used as the possessive here)

2020-05-13 13:54 UTC, sverhoeven commented on CONTRIBUTING.rst
> +
I would rather remove the `Documentation for maintainers` heading in README and keep it here.

2020-05-13 13:55 UTC, sverhoeven commented on CONTRIBUTING.rst
> +1. Check author list in citation.cff and .zenodo.json
Done

2020-05-13 14:04 UTC, sverhoeven commented on CONTRIBUTING.rst
> +4. Goto [GitHub release page](https://github.com/matchms/matchms/releases)
fixed

2020-05-13 14:18 UTC, jspaaks approved these changes
:+1:

2020-05-13 14:19 UTC, merged

2021-04-06 20:23 UTC, hechth commented on .github/workflows/CI_build.yml
> +            --channel bioconda -v \
What is the motivation for the change in order? Just asking out of curiosity 👍