Add precursor_mz harmonization and make sure losses are calculated.
matchms/matchms-backup pull request #224
Opened 2020-05-14 11:46 UTC by florian-huber

Addressing #211

2020-05-14 12:26 UTC, fdiblen commented on integration-tests/test_user_workflow_spec2vec.py
> +    repository_root = os.path.join(os.path.dirname(__file__), '..')
use double quotes

2020-05-14 12:28 UTC, fdiblen commented on integration-tests/test_user_workflow_spec2vec.py
> +    assert "loss@66.1" in model.wv.vocab, 'Word should be in corpus and model.'
add to a separate test

2020-05-14 12:38 UTC, fdiblen commented on matchms/filtering/harmonize_precursor_mz.py
> +            spectrum.set("precursor_mz", pepmass[0])
add a test to at least check the type

2020-05-14 12:40 UTC, fdiblen requested changes
Cool. requested few changes.

2020-05-14 12:53 UTC, florian-huber commented on integration-tests/test_user_workflow_spec2vec.py
> +    repository_root = os.path.join(os.path.dirname(__file__), '..')
Done.

2020-05-14 12:54 UTC, florian-huber commented on integration-tests/test_user_workflow_spec2vec.py
> +    assert "loss@66.1" in model.wv.vocab, 'Word should be in corpus and model.'
Remove this. 
Will add it as a new test in a next PR (which will deal more in depth with the ``add_losses`` function.

2020-05-14 12:59 UTC, florian-huber commented on matchms/filtering/harmonize_precursor_mz.py
> +            spectrum.set("precursor_mz", pepmass[0])
Done.

2020-05-15 11:24 UTC, florian-huber commented
@fdiblen Thanks for reviewing! 
I added changes as response to your comments. Let me know if they are resolved so I can merge this PR.

2020-05-18 12:35 UTC, fdiblen approved these changes
:swan:

2020-05-18 13:50 UTC, florian-huber commented
Thanks Faruk.

2020-05-18 13:51 UTC, merged