updated github repo badge
matchms/matchms-backup pull request #27
Opened 2020-03-19 16:05 UTC by jspaaks

2020-03-19 16:17 UTC, jspaaks commented
All badges updated except PyPI (pending #13 )

2020-03-19 16:19 UTC, fdiblen commented on README.rst
>  .. |License Badge| image:: https://img.shields.io/github/license/citation-file-format/cff-converter-python
this is a badge for cff-converter

2020-03-19 16:19 UTC, fdiblen commented on README.rst
>  .. |PyPI Badge| image:: https://img.shields.io/pypi/v/cffconvert.svg?colorB=blue
cff-corverter again

2020-03-19 16:21 UTC, fdiblen commented on README.rst
> +   :target: https://doi.org/10.5281/zenodo.3716379
Zenodo  title says Spec2Vec but github repo etc are all pointing to matchms

2020-03-19 16:23 UTC, fdiblen requested changes
Some changes needed for the badges and Zenodo

2020-03-19 16:45 UTC, merged

2020-05-18 20:00 UTC, florian-huber commented
I implemented the numba based cosine similarity score in PR matchms/matchms-backup#239

2020-05-19 12:40 UTC, florian-huber commented
@HannoSpreeuw The test_user_workflow you had is pretty close to a realistic workflow. In my case I want to get the similarities between all spectra and I would would run it slightly differently as shown in the following example. The main difference is that this will compute a similarity score matrix and not a detailed list with spectrums inside.
```python
import os
import pytest
from matchms import calculate_scores, Scores
from matchms.filtering import add_parent_mass
from matchms.filtering import default_filters
from matchms.filtering import normalize_intensities
from matchms.filtering import require_minimum_number_of_peaks
from matchms.filtering import select_by_mz
from matchms.filtering import select_by_relative_intensity
from matchms.importing import load_from_mgf
from matchms.similarity import CosineGreedy


def apply_my_filters(s):
    s = default_filters(s)
    s = add_parent_mass(s)
    s = normalize_intensities(s)
    s = select_by_relative_intensity(s, intensity_from=0.01, intensity_to=1.0)
    s = select_by_mz(s, mz_from=0, mz_to=1000)
    s = require_minimum_number_of_peaks(s, n_required=5)
    return s

module_root = os.path.join(os.path.dirname(__file__), "..")
spectrums_file = os.path.join(module_root, "tests", "pesticides.mgf")

# apply my filters to the data
spectrums = [apply_my_filters(s) for s in load_from_mgf(spectrums_file)]

# omit spectrums that didn't qualify for analysis
spectrums = [s for s in spectrums if s is not None]

# define similarity function
cosine_greedy = CosineGreedy()

# this will be a library grouping analysis, so queries = references = spectrums
queries = spectrums[:]
references = spectrums[:]

similarity_matrix = Scores(references=5*references,
                           queries=5*queries,
                           similarity_function=cosine_greedy).calculate().scores
```

I added an alternative implementation of the cosine score, which would be ``from matchms.similarity import CosineGreedyNumba`` and is in PR matchms/matchms-backup#239.

I think that the above implementation should be a good starting point for profiling. But there is clearly be a lot of room for performance gains. Each similarity score is calculated separately, so threading should bring some extra gains. 

And in the concrete example above we also "loose" a factor of 2 because queries and references are identical, and similarity_matrix[a,b] is the same score as similarity_matrix[b,a], but here will be calculated twice.

2020-05-20 10:08 UTC, jspaaks commented
> And in the concrete example above we also "loose" a factor of 2 because queries and references are identical, and similarity_matrix[a,b] is the same score as similarity_matrix[b,a], but here will be calculated twice.

You may want to introduce a new argument ``is_symmetrical=False`` to ``Scores.calculate`` and ``Scores.calculate_parallel``. Or alteratively, to the constructor of ``Scores``.

2020-05-20 11:36 UTC, HannoSpreeuw commented
@florian-huber for profiling results of [that code](https://github.com/matchms/matchms/issues/238#issuecomment-630791026), see matchms/matchms#8