Add Github actions
matchms/matchms-backup pull request #28
Opened 2020-03-20 08:57 UTC by fdiblen

2020-03-20 10:14 UTC, fdiblen commented
- Openbabel should be fixed. See #31 
- I disabled linting which will be addressed by #32

2020-03-20 10:35 UTC, jspaaks requested changes

2020-03-20 10:35 UTC, jspaaks commented on .github/workflows/pythonapp.yml
> +# This workflow will install Python dependencies, run tests and lint with a single version of Python
maybe we should delete this comment, as it doesn;t add much and is already out of date

2020-03-20 10:35 UTC, jspaaks commented on .github/workflows/pythonapp.yml
> +    #     pytest
commented-out code should be deleted

2020-03-20 10:35 UTC, jspaaks commented on .github/workflows/pythonapp.yml
> +    #     twine upload dist/*
commented-out code should be deleted

2020-03-20 10:35 UTC, jspaaks commented on .github/workflows/pythonapp.yml
> +  deploy:
I'm not a fan of automatically deploying to PyPI. I'd be interested to see what others think about this.

2020-03-20 10:43 UTC, jspaaks commented
Also, I'd like to see ``pythonapp.yaml`` renamed to something more descriptive/accurate. Maybe ``ci.yaml``?

2020-03-20 12:13 UTC, fdiblen commented on .github/workflows/pythonapp.yml
> +# This workflow will install Python dependencies, run tests and lint with a single version of Python
agreed

2020-03-20 12:18 UTC, fdiblen commented on .github/workflows/pythonapp.yml
> +    #     pytest
this was there because we will add those in other issues. I will remove these lines

2020-03-20 12:18 UTC, fdiblen commented on .github/workflows/pythonapp.yml
> +    #     twine upload dist/*
done

2020-03-20 12:18 UTC, fdiblen commented on .github/workflows/pythonapp.yml
> +  deploy:
@sverhoeven ?

2020-03-20 12:19 UTC, fdiblen commented
> Also, I'd like to see `pythonapp.yaml` renamed to something more descriptive/accurate. Maybe `ci.yaml`?

done

2020-03-24 09:39 UTC, sverhoeven commented on .github/workflows/pythonapp.yml
> +  deploy:
if it is tied with a Github release then I dont have a problem with it.

2020-03-24 10:59 UTC, sverhoeven requested changes
Rest looks OK

2020-03-24 10:59 UTC, sverhoeven commented on .github/workflows/ci_deploy.yml
> +    - name: Publish package
The publish action expects dist/ dir to be filled. 

Please add a step to run `python setup.py bdist_wheel`.

2020-03-24 16:54 UTC, fdiblen commented on .github/workflows/ci_deploy.yml
> +    - name: Publish package
added to ci_deploy.yml.
We will need to change this because now we are using anaconda to build.

2020-03-24 17:28 UTC, jspaaks approved these changes
Looks good to me. Glad you got it running!

2020-03-24 17:31 UTC, jspaaks commented on .github/workflows/ci_build.yml
>          shell: pwsh
i would have expected bash, but ok.

2020-03-25 14:33 UTC, merged

2020-03-25 16:58 UTC, CunliangGeng commented
It seems the Action is triggered after merging pull request. Is it possible to trigger it when creating a PR?

2020-05-20 09:49 UTC, jspaaks commented
PR matchms/matchms-backup#244