implemented simple Spectrum
matchms/matchms-backup pull request #66
Opened 2020-04-01 16:30 UTC by jspaaks

still needs test

2020-04-01 17:28 UTC, jspaaks commented
In progress
- https://github.com/matchms/matchms/pull/66
- https://github.com/matchms/notebooks/pull/13

2020-04-02 07:39 UTC, florian-huber commented
Thanks for the start here!
I will now move code into the classes and functions (trying hard not to break it...).

2020-04-02 08:00 UTC, jspaaks commented
@florian-huber Maybe it's a good idea to go slow, this will give the other team members time to refactor, add tests, and provide feedback to new code being introduced.

2020-04-02 09:26 UTC, jspaaks commented
hallelujah green tests

2020-04-03 13:19 UTC, fdiblen requested changes
@sverhoeven and me checked it together. please check our suggestions.

2020-04-03 13:19 UTC, fdiblen commented on matchms/Scores.py
> +        self.scores = numpy.empty([len(self.reference_spectrums),
Why are you using numpy here but not only Python lists?

2020-04-03 13:19 UTC, fdiblen commented on matchms/Spectrum.py
> +# file: matchms/Spectrum.py
be consistent either to have this line in all files or not

2020-04-03 13:19 UTC, fdiblen commented on matchms/Spectrum.py
> +    def interpret_pepmass(self):
should that be a private function?
like:
`def _interpret_pepmass(self):`

2020-04-03 13:19 UTC, fdiblen commented on matchms/Spectrum.py
> +    def ion_masses(self, precursormass, int_charge):
should that be a private function?

2020-04-03 13:19 UTC, fdiblen commented on matchms/Spectrum.py
> +    def interpret_charge(self, charge):
should that be a private function?

2020-04-03 13:19 UTC, fdiblen commented on matchms/__init__.py
`from .__version__ import __version__` is missing

2020-04-03 13:19 UTC, fdiblen commented on matchms/calculate_scores.py
> +from matchms.Scores import Scores
it should be:
`from .Scores import Scores`

2020-04-03 13:19 UTC, fdiblen commented on matchms/calculate_scores.py
> +
the content of the calculate function in matchms/Scores.py should be moved here or remove this file. We prefer to move the function content here.

2020-04-03 13:19 UTC, fdiblen commented on matchms/importing/load_from_mgf.py
> +from matchms.Spectrum import Spectrum
importing should change:
`from ..Spectrum import Spectrum`

2020-04-03 13:19 UTC, fdiblen commented on matchms/importing/load_from_mgf.py
> +    return [Spectrum(s) for s in list(MGF(filename, convert_arrays=1))]
remove the extra list:
`    return [Spectrum(s) for s in MGF(filename, convert_arrays=1)]`

2020-04-03 13:19 UTC, fdiblen commented on tests/old/test_helper_functions.py
>  import numpy as np
just curious: how did you do the formatting? Is it your editor or some tools like black?

2020-04-03 13:20 UTC, sverhoeven commented on matchms/Spectrum.py
> +    def interpret_charge(self, charge):
as the function is only useful in the constructor

2020-04-03 13:22 UTC, sverhoeven approved these changes
See comments of Faruk

2020-04-03 13:32 UTC, jspaaks commented on matchms/Scores.py
> +        self.scores = numpy.empty([len(self.reference_spectrums),
because the manipulation later on requires it

2020-04-03 13:33 UTC, florian-huber commented on matchms/Spectrum.py
> +    def interpret_charge(self, charge):
Yes, all those functions will be removed from the Spectrum class and will become filters.

2020-04-03 13:33 UTC, jspaaks commented on matchms/Spectrum.py
> +# file: matchms/Spectrum.py
I removed it in the next PR (coming up). It was left over from https://github.com/matchms/matchms/issues/63#issuecomment-607164850, where readers do not have that context.

2020-04-03 13:34 UTC, jspaaks commented on matchms/Spectrum.py
> +    def interpret_pepmass(self):
This function was removed altogether in the upcoming PR

2020-04-03 13:34 UTC, jspaaks commented on matchms/Spectrum.py
> +    def ion_masses(self, precursormass, int_charge):
This function was removed altogether in the upcoming PR

2020-04-03 13:34 UTC, jspaaks commented on matchms/Spectrum.py
> +    def interpret_charge(self, charge):
This function was removed altogether in the upcoming PR

2020-04-03 13:35 UTC, jspaaks commented on matchms/__init__.py
prospector complained that it was not used. which it was right about. You should still see it when you do an ``import matchms`` though.

2020-04-03 13:37 UTC, jspaaks commented on matchms/calculate_scores.py
> +from matchms.Scores import Scores
changed in the next PR

2020-04-03 13:39 UTC, jspaaks commented on matchms/importing/load_from_mgf.py
> +from matchms.Spectrum import Spectrum
changed in the next PR

2020-04-03 13:45 UTC, jspaaks commented on tests/old/test_helper_functions.py
>  import numpy as np
not exactly sure because part of what is now under ``old`` was overwritten by Florian's work, see my earlier PR https://github.com/matchms/matchms/pull/50. But, I just blindly applied yapf as per @CunliangGeng 's suggestion https://github.com/matchms/matchms/issues/32#issuecomment-604360565

2020-04-03 13:47 UTC, jspaaks commented
Thanks both @fdiblen and @sverhoeven for the review. I accepted all of your comment in the next PR, except 1 "the content of the calculate function in matchms/Scores.py should be moved here or remove this file. We prefer to move the function content here." I propose that we first merge, then we can discuss this later so it's not blocking other developments.

2020-04-03 13:49 UTC, fdiblen commented
> Thanks both @fdiblen and @sverhoeven for the review. I accepted all of your comment in the next PR, except 1 "the content of the calculate function in matchms/Scores.py should be moved here or remove this file. We prefer to move the function content here." I propose that we first merge, then we can discuss this later so it's not blocking other developments.

Agreed.

2020-04-03 13:50 UTC, fdiblen approved these changes

2020-04-03 13:50 UTC, jspaaks commented on matchms/importing/load_from_mgf.py
> +    return [Spectrum(s) for s in list(MGF(filename, convert_arrays=1))]
This already changed in the next PR

2020-04-03 13:50 UTC, fdiblen commented
Good to merge.

2020-04-03 13:50 UTC, merged