63 followup
matchms/matchms-backup pull request #67
Opened 2020-04-03 13:57 UTC by jspaaks

follow up of #66 

refs 
- https://github.com/matchms/matchms/issues/51
- https://github.com/matchms/matchms/issues/63
- https://github.com/matchms/matchms/issues/64
- https://github.com/matchms/matchms/issues/65
- https://github.com/matchms/matchms/issues/41
- https://github.com/matchms/matchms/issues/56
- https://github.com/matchms/matchms/issues/52

with this PR, a user should now be able to do:

```python

import os
from matchms.importing import load_from_mgf
from matchms.filtering import filterfun1, filterfun2
from matchms.similarity import SimMeas1, IntersectMz
from matchms import calculate_scores

def test_user_workflow():

    def apply_filters(s):
        filterfun1(s)
        filterfun2(s)

    # loading
    module_root = os.path.join(os.path.dirname(__file__), '..')
    references_file = os.path.join(module_root, 'tests', 'pesticides.mgf')

    reference_spectrums_raw = load_from_mgf(references_file)
    reference_spectrums = [s.clone() for s in reference_spectrums_raw]

    query_spectrum_raw = reference_spectrums_raw[0]
    query_spectrum = query_spectrum_raw.clone()

    # filtering
    for s in reference_spectrums:
        apply_filters(s)

    apply_filters(query_spectrum)

    # define similarity functions
    similarity_functions = [SimMeas1("simmeas1", factor=0.1), IntersectMz("intersect")]

    # calculate_scores
    scores = calculate_scores(query_spectrum,
                              reference_spectrums,
                              similarity_functions).sort_by("intersect").reverse().top(10)

    print(scores)

if __name__ == '__main__':
    test_user_workflow()

```

2020-04-03 15:01 UTC, florian-huber commented on matchms/filtering/filterfun1.py
> +
I guess it's clear from the function name. But should there still be an extra explanation for this? Such as """Toy filter function."""

2020-04-03 15:04 UTC, florian-huber approved these changes
Looks good to me @jspaaks, thanks!
I think I can indeed more easily start working from here on.
(my only comment was that most functions so far are toy functions which could also be stated more clearly in the comments... but they will anyway be replaced soon)

2020-04-03 16:31 UTC, jspaaks commented on matchms/filtering/filterfun1.py
> +
updated.

2020-04-06 07:16 UTC, florian-huber commented
@jspaaks, I re-wrote part of the harmonization according to the new code structure. Should I add it to this PR or better wait until this is merged (and start a new PR) ?

2020-04-06 07:34 UTC, jspaaks commented
Better wait until this is merged. It is good practice anyway to have small PRs, and have them focus on one aspect of the code. Of course, for such a practice to work, it is the team's responsibility that PRs don't just sit there for more than a few days at most.

2020-04-06 08:35 UTC, fdiblen commented on matchms/Scores.py
> +    def sort_by(self, label, kind='quicksort'):
I think this assumes label is unique in the array. Is that right?

2020-04-06 08:41 UTC, fdiblen commented on matchms/Scores.py
> +        for i_simfun, simfun in enumerate(self.similarity_functions):
instead of this for loop, you can do:
indexes = [i for i,x in enumerate(similarity_functions) if x == 'foo']

2020-04-06 08:45 UTC, fdiblen commented on matchms/Scores.py
> +        reference_spectrums = [s.clone() for s in self.reference_spectrums[:n]]
for me it is clear what these functions do but we should add docstring for the auto generated developer documentation.

2020-04-06 08:47 UTC, fdiblen commented on matchms/Spectrum.py
> -    def interpret_pepmass(self):
will these functions implemented later?

2020-04-06 08:47 UTC, fdiblen commented on matchms/Spectrum.py
> +        plt.ylabel('Intensity')
needs `plt.show()` or you need to return plt?

2020-04-06 08:50 UTC, fdiblen commented on matchms/__init__.py
> -    "harmonization",
does that mean you will implement harmonization later?

2020-04-06 08:51 UTC, fdiblen commented on matchms/filtering/__init__.py
> +from .filterfun1 import filterfun1
shall we create issues about filterfun1, filterfun2 etc.?

2020-04-06 08:56 UTC, fdiblen requested changes
Looks good. 
I added few comments.

2020-04-06 09:01 UTC, florian-huber commented on matchms/Scores.py
> +    def sort_by(self, label, kind='quicksort'):
It could make sense to here use **lexsort** instead of **argsort**. That would allow more complex sorting (using different labels and giving them different preferences. That is actually what people to a lot, e.g. sort by precursor_mass-match and score1 and score2...

2020-04-06 09:21 UTC, jspaaks commented on matchms/Scores.py
> +    def sort_by(self, label, kind='quicksort'):
does it matter at this stage? perfect is the enemy of good remember

2020-04-06 09:23 UTC, jspaaks commented on matchms/Scores.py
> +        for i_simfun, simfun in enumerate(self.similarity_functions):
I deliberately did it naively for better legibility ("premature optimization is the root of all evil")

To be clear, this part will need to see parallelization (after we do a performance analysis later).

2020-04-06 09:23 UTC, jspaaks commented on matchms/Scores.py
> +        reference_spectrums = [s.clone() for s in self.reference_spectrums[:n]]
indeed, later

2020-04-06 09:24 UTC, jspaaks commented on matchms/Spectrum.py
> -    def interpret_pepmass(self):
yes, but not here. They will be implemented as filters.

2020-04-06 09:25 UTC, jspaaks commented on matchms/Spectrum.py
> +        plt.ylabel('Intensity')
needs plt.show, but not inside the method.

2020-04-06 09:26 UTC, jspaaks commented on matchms/__init__.py
> -    "harmonization",
it means that ``harmonization`` was renamed to ``filtering``

2020-04-06 09:28 UTC, jspaaks commented on matchms/filtering/__init__.py
> +from .filterfun1 import filterfun1
They have been created already, e.g. 
- https://github.com/matchms/matchms/issues/53
- https://github.com/matchms/matchms/issues/54
- https://github.com/matchms/matchms/issues/55

2020-04-06 09:50 UTC, fdiblen commented on matchms/Spectrum.py
> +        plt.ylabel('Intensity')
then you will need to return the figure?

2020-04-06 09:50 UTC, fdiblen commented on matchms/__init__.py
> -    "harmonization",
much better :)

2020-04-06 10:17 UTC, jspaaks commented on matchms/Spectrum.py
> +        plt.ylabel('Intensity')
Not super familiar with matplotlib, but I'd expect to return a handle to the axis, not the figure. However, to me that's all details that should not block the merging of this PR in my opinion.

Having the PR like it is, does not break anythin and is an improvement over what we had. At this stage I think we should focus on fleshing out the skeleton, and not get hung up on details. That way, we are able to discover flaws in the design before we are too invested in the implementation.

2020-04-06 10:24 UTC, fdiblen approved these changes

2020-04-06 10:30 UTC, jspaaks commented
Thanks for reviewing @fdiblen , @florian-huber !

2020-04-06 10:30 UTC, merged

2020-04-06 11:06 UTC, florian-huber commented on matchms/Scores.py
> +    def sort_by(self, label, kind='quicksort'):
Probably true :)