Readthedocs
matchms/matchms-backup pull request #77
Opened 2020-04-06 18:30 UTC by jspaaks

2020-04-06 18:43 UTC, fdiblen commented on readthedocs/requirements.txt
> +numpy
Do we really need numpy and matplotlib? :roll_eyes:

2020-04-06 18:48 UTC, fdiblen commented on readthedocs/Makefile
>  # Minimal makefile for Sphinx documentation
This is a better Makefile:
https://github.com/readthedocs/readthedocs.org/blob/master/docs/Makefile

2020-04-06 18:49 UTC, fdiblen commented on readthedocs/make.bat
> +@ECHO OFF
this is for the bat file:
https://github.com/readthedocs/readthedocs-build/blob/master/integration_tests/minimal_project/make.bat

2020-04-06 18:50 UTC, jspaaks commented on readthedocs/requirements.txt
> +numpy
Yes, we do (i do not understand why). Something to look into later I guess

2020-04-06 18:50 UTC, jspaaks commented on readthedocs/Makefile
>  # Minimal makefile for Sphinx documentation
better how?

2020-04-06 18:51 UTC, fdiblen commented on readthedocs/source/index.rst
> +Welcome to Getting Started with Sphinx's documentation!
Sphinx's documentation --> matchms's documentation

2020-04-06 18:52 UTC, fdiblen commented on readthedocs/source/index.rst
> +   :maxdepth: 2
shall we change maxdepth to 3?

2020-04-06 18:52 UTC, jspaaks commented on readthedocs/make.bat
> +@ECHO OFF
I used some tools to automatically generate the skeleton. I find the ``conf.py``, ``Makefile``, and ``make.bat`` very difficult to understand to the point where I don't dare to touch them.

2020-04-06 18:53 UTC, fdiblen requested changes
I suggested few minor changes

2020-04-06 18:53 UTC, jspaaks commented on readthedocs/source/index.rst
> +Welcome to Getting Started with Sphinx's documentation!
myea later

2020-04-06 18:53 UTC, jspaaks commented on readthedocs/source/index.rst
> +   :maxdepth: 2
Sure

2020-04-06 18:56 UTC, jspaaks commented
Hey cool sonarcloud

2020-04-07 08:59 UTC, jspaaks commented
Not perfect by any means, but I've had it with readthedocs, sphinx and sphinxcontrib-apidoc

2020-04-07 11:13 UTC, fdiblen commented on readthedocs/Makefile
>  # Minimal makefile for Sphinx documentation
extra build options such as generating pdf and some other formats. Not a big deal for now though.

2020-04-07 14:34 UTC, fdiblen approved these changes

2020-04-07 14:36 UTC, merged