added select-by capability based on mz and intensity
matchms/matchms-backup pull request #87
Opened 2020-04-07 16:52 UTC by jspaaks

- added tests
- updated module exports

refs #54

2020-04-08 16:32 UTC, fdiblen commented on matchms/filtering/select_by_intensity.py
> +def select_by_intensity(spectrum, intensity_from=10.0, intensity_to=200.0):
can we add docstrings please.

2020-04-08 16:32 UTC, fdiblen commented on matchms/filtering/select_by_mz.py
> +def select_by_mz(spectrum, mz_from=0.0, mz_to=1000.0):
docstrings

2020-04-08 16:33 UTC, jspaaks commented on matchms/filtering/select_by_intensity.py
> +def select_by_intensity(spectrum, intensity_from=10.0, intensity_to=200.0):
can we do it later

2020-04-08 16:33 UTC, jspaaks commented on matchms/filtering/select_by_mz.py
> +def select_by_mz(spectrum, mz_from=0.0, mz_to=1000.0):
later

2020-04-08 16:34 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_no_bounds():
can we add docstrings please?

2020-04-08 16:39 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 2
numpy has shape and size functions. Please use these functions if you need to check the 'length'

2020-04-08 16:41 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 1
can you add assertion messages? something like in matchms/filtering/select_by_intensity.py

2020-04-08 16:42 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_lower_bound_only():
add docstring

2020-04-08 16:42 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_upper_bound_only():
add intensity_from to function arguments

2020-04-08 16:44 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 1
I will

2020-04-08 16:44 UTC, fdiblen commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_no_bounds_2():
more descriptive function name is needed

2020-04-08 16:46 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 2
I think we can agree this is a detail, right? The code is not wrong as it is, i.e. we do not have a problem in this actual moment. But, importantly, while I'm working to implement the requested changes, the rest of the team is waiting until they are starting to see the outline of the refactored structure.

When reviewing pull requests, I go by the following rules of thumb
1. Does the PR break any of the existing stuff
1. Is the PR an improvement over what is there already

if 1 is no and 2 is yes, we can merge.

2020-04-08 16:48 UTC, fdiblen commented on tests/test_select_by_mz.py
> +def test_select_by_mz_no_bounds_2():
find a better name

2020-04-08 16:50 UTC, fdiblen requested changes
@jspaaks  Nice!
Requested some changes. If you could add docstrings too all functions it would be great.
Do we want to have _select top X by intensity/mz_ function as well?
There is also a conflict in matchms/filtering/__init__.py

2020-04-08 16:58 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 1
I started work on adding assert messages but noticed that I was making it worse. Compare the two snippets below; the first one without assert messages, the second with assert messages added. Which do you find more readable?

```python
assert len(spectrum.mz) == 2, "Expected the spectrum's mz to have been filtered down to just 2 elements."
assert len(spectrum.mz) == len(spectrum.intensities), "Expected the spectrum's mz to be equal in length to its " \
                                                  "intensities."
assert numpy.array_equal(spectrum.mz, numpy.array([20, 30], dtype="float")), "Expected spectrum's mz array to be " \
                                                                         "equal to [20, 30]"
assert numpy.array_equal(spectrum.intensities, numpy.array([10, 100], dtype="float")), "Expected spectrum's "\
                                                                                   "intensities to be equal " \
                                                                                   "to [10, 100]"
```


```python
assert len(spectrum.mz) == 2
assert len(spectrum.mz) == len(spectrum.intensities)
assert numpy.array_equal(spectrum.mz, numpy.array([20, 30], dtype="float"))
assert numpy.array_equal(spectrum.intensities, numpy.array([10, 100], dtype="float"))
```

If readability is the only argument, I think we should omit assert messages if the message does not add to the statement. But perhaps there are other arguments that I'm forgetting?

2020-04-08 17:04 UTC, jspaaks commented
- I'm reluctant to start adding docstrings to test functions; the filter functions yes, we should do that (although not now, I'd like us to focus on laying out the general structure before filling in the details)
- About _select top X by intensity/mz_ on what data do you see this operating (``Spectrum``, ``Scores.scores``, maybe something else)?
- I'll fix the conflict

2020-04-08 17:25 UTC, jspaaks commented
The conflict is resolved, but now prospector will complain about it.

2020-04-08 17:31 UTC, jspaaks commented on tests/test_select_by_mz.py
> +def test_select_by_mz_no_bounds_2():
renamed to test_select_by_mz_no_parameters_2 and moved it adjacent to test_select_by_mz_no_parameters_1 at the top of the file.

2020-04-08 17:54 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_no_bounds():
I don't want to do this for unit test functions

2020-04-08 17:54 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +    assert len(spectrum.mz) == 2
updated to use numpy ndarray.size

2020-04-08 17:54 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_lower_bound_only():
I don't want to do this for unit test functions

2020-04-08 17:55 UTC, jspaaks commented on tests/test_select_by_intensity.py
> +def test_select_by_intensity_no_bounds_2():
changed it to ``test_select_by_intensity_no_parameters_2``

2020-04-09 11:26 UTC, jspaaks commented
OK ladies. Enough chit-chat, I'm merging this.

2020-04-09 11:26 UTC, merged